<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>LumenEditor.Windows.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jint" Version="4.16.1" />
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>
</Project>
